project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!*.md"
execute:
  freeze: auto
author:
  - name: Benedek Kaibas
    email: kaibas01@allegheny.edu
website:
  title: "An Empirical Study on Static Analyzer Toolsets to Reduce False Positives, False Negatives in Python Type Checkers"
  navbar:
    right:
      - text: "Senior Thesis"
        href: thesis/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/benedekaibas
format:
  html:
    theme: journal
    css: styles.css
